Rebrand table indexes
wintercms/wn-translate-plugin pull request #5
Opened 2021-04-26 22:15 UTC by matteotrubini

Ensure coherence in schema definitions

2021-04-26 23:19 UTC, mjauvin requested changes
No need to pass argument twice.

2021-04-26 23:19 UTC, mjauvin commented on updates/v2.0.1/rename_indexes.php
> +            $this->updateIndexNames($from, $to, $from);
```suggestion
            $this->updateIndexNames($from, $to);
```

2021-04-26 23:19 UTC, mjauvin commented on updates/v2.0.1/rename_indexes.php
> +    public function updateIndexNames($from, $to, $table)
```suggestion
    public function updateIndexNames($from, $to)
```

2021-04-26 23:19 UTC, mjauvin commented on updates/v2.0.1/rename_indexes.php
> +    {
```suggestion
    {
        $table = $from;
```

2021-04-26 23:20 UTC, mjauvin commented on updates/v2.0.1/rename_indexes.php
> +            $this->updateIndexNames($from, $to, $to);
```suggestion
            $this->updateIndexNames($from, $to);
```

2021-04-27 02:18 UTC, merged

2021-04-27 02:18 UTC, mjauvin commented
Thanks!

2021-04-27 07:27 UTC, matteotrubini commented
> Excume my previous modification requests, I had a brain cramp when I wrote this... ;)

Mee too when I choosen variables like a nursery rhyme  :hand_over_mouth: